/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f8fafb",
        "surface-dim": "#d8dadb",
        "on-tertiary-container": "#48ab4d",
        "primary-container": "#00334e",
        primary: "#001d2f",
        tertiary: "#002104",
        "on-surface-variant": "#42474d",
        "on-secondary-fixed": "#0f1d28",
        "on-tertiary-fixed-variant": "#005313",
        "surface-container-high": "#e6e8e9",
        secondary: "#52606d",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#94f990",
        "surface-container": "#eceeef",
        outline: "#72787e",
        "on-secondary-container": "#586673",
        "on-primary-container": "#759cbb",
        "secondary-fixed": "#d5e4f3",
        "primary-fixed": "#cae6ff",
        "tertiary-fixed-dim": "#78dc77",
        "on-tertiary-fixed": "#002204",
        "surface-container-highest": "#e1e3e4",
        "on-primary": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f2f4f5",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#bac8d7",
        "primary-fixed-dim": "#a4cbec",
        "on-primary-fixed-variant": "#214a66",
        "surface-tint": "#3b627f",
        "on-secondary-fixed-variant": "#3a4854",
        "secondary-container": "#d5e4f3",
        "outline-variant": "#c2c7ce",
        "inverse-primary": "#a4cbec",
        "tertiary-container": "#00390a",
        "inverse-on-surface": "#eff1f2",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001e30",
        background: "#f8fafb",
        "on-surface": "#191c1d",
        "surface-bright": "#f8fafb",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};
