/** @type {import("tailwindcss").Config} */
module.exports = {
        content: ["./index.html"],
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "surface-container-highest": "#e1e3e4",
                    "background": "#f8f9fa",
                    "surface-container-low": "#f3f4f5",
                    "surface": "#f8f9fa",
                    "surface-container": "#edeeef",
                    "on-secondary": "#ffffff",
                    "on-tertiary-fixed": "#2b1700",
                    "error": "#ba1a1a",
                    "on-surface": "#191c1d",
                    "inverse-primary": "#adc7f7",
                    "primary-fixed": "#d6e3ff",
                    "on-primary-fixed-variant": "#2d476f",
                    "on-secondary-fixed": "#002111",
                    "tertiary-fixed": "#ffddba",
                    "surface-container-lowest": "#ffffff",
                    "on-tertiary": "#ffffff",
                    "tertiary": "#321b00",
                    "on-error-container": "#93000a",
                    "outline-variant": "#c4c6cf",
                    "surface-bright": "#f8f9fa",
                    "on-tertiary-container": "#c6955e",
                    "on-surface-variant": "#43474e",
                    "error-container": "#ffdad6",
                    "secondary-fixed-dim": "#83d8a6",
                    "secondary-container": "#9ff5c1",
                    "on-background": "#191c1d",
                    "tertiary-container": "#4f2e00",
                    "surface-tint": "#455f88",
                    "on-secondary-container": "#167249",
                    "inverse-surface": "#2e3132",
                    "surface-container-high": "#e7e8e9",
                    "on-error": "#ffffff",
                    "secondary-fixed": "#9ff5c1",
                    "inverse-on-surface": "#f0f1f2",
                    "on-primary-container": "#86a0cd",
                    "on-secondary-fixed-variant": "#005231",
                    "surface-variant": "#e1e3e4",
                    "surface-dim": "#d9dadb",
                    "on-tertiary-fixed-variant": "#633f0f",
                    "tertiary-fixed-dim": "#f2bc82",
                    "secondary": "#0a6c44",
                    "primary-fixed-dim": "#adc7f7",
                    "primary-container": "#1a365d",
                    "outline": "#74777f",
                    "on-primary-fixed": "#001b3c",
                    "primary": "#002045",
                    "on-primary": "#ffffff"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "fontFamily": {
                    "headline": ["ManropeLocal", "system-ui", "sans-serif"],
                    "body": ["system-ui", "sans-serif"],
                    "label": ["system-ui", "sans-serif"]
            }
          },
        },
      }
